//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfBasicProject.UrunServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDTO", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service.Dto.DtoModels")]
    [System.SerializableAttribute()]
    public partial class ProductDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityPerUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuantityPerUnit {
            get {
                return this.QuantityPerUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityPerUnitField, value) != true)) {
                    this.QuantityPerUnitField = value;
                    this.RaisePropertyChanged("QuantityPerUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UrunServiceReference.IServiceRepositoryOf_ProductDTO")]
    public interface IServiceRepositoryOf_ProductDTO {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRepositoryOf_ProductDTO/GetList", ReplyAction="http://tempuri.org/IServiceRepositoryOf_ProductDTO/GetListResponse")]
        System.Collections.Generic.List<WcfBasicProject.UrunServiceReference.ProductDTO> GetList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRepositoryOf_ProductDTO/GetList", ReplyAction="http://tempuri.org/IServiceRepositoryOf_ProductDTO/GetListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WcfBasicProject.UrunServiceReference.ProductDTO>> GetListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRepositoryOf_ProductDTO/Get", ReplyAction="http://tempuri.org/IServiceRepositoryOf_ProductDTO/GetResponse")]
        WcfBasicProject.UrunServiceReference.ProductDTO Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRepositoryOf_ProductDTO/Get", ReplyAction="http://tempuri.org/IServiceRepositoryOf_ProductDTO/GetResponse")]
        System.Threading.Tasks.Task<WcfBasicProject.UrunServiceReference.ProductDTO> GetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRepositoryOf_ProductDTO/Add", ReplyAction="http://tempuri.org/IServiceRepositoryOf_ProductDTO/AddResponse")]
        bool Add(WcfBasicProject.UrunServiceReference.ProductDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRepositoryOf_ProductDTO/Add", ReplyAction="http://tempuri.org/IServiceRepositoryOf_ProductDTO/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(WcfBasicProject.UrunServiceReference.ProductDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRepositoryOf_ProductDTO/Update", ReplyAction="http://tempuri.org/IServiceRepositoryOf_ProductDTO/UpdateResponse")]
        bool Update(WcfBasicProject.UrunServiceReference.ProductDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRepositoryOf_ProductDTO/Update", ReplyAction="http://tempuri.org/IServiceRepositoryOf_ProductDTO/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(WcfBasicProject.UrunServiceReference.ProductDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRepositoryOf_ProductDTO/Delete", ReplyAction="http://tempuri.org/IServiceRepositoryOf_ProductDTO/DeleteResponse")]
        bool Delete(WcfBasicProject.UrunServiceReference.ProductDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRepositoryOf_ProductDTO/Delete", ReplyAction="http://tempuri.org/IServiceRepositoryOf_ProductDTO/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(WcfBasicProject.UrunServiceReference.ProductDTO entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceRepositoryOf_ProductDTOChannel : WcfBasicProject.UrunServiceReference.IServiceRepositoryOf_ProductDTO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceRepositoryOf_ProductDTOClient : System.ServiceModel.ClientBase<WcfBasicProject.UrunServiceReference.IServiceRepositoryOf_ProductDTO>, WcfBasicProject.UrunServiceReference.IServiceRepositoryOf_ProductDTO {
        
        public ServiceRepositoryOf_ProductDTOClient() {
        }
        
        public ServiceRepositoryOf_ProductDTOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceRepositoryOf_ProductDTOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRepositoryOf_ProductDTOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRepositoryOf_ProductDTOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WcfBasicProject.UrunServiceReference.ProductDTO> GetList() {
            return base.Channel.GetList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WcfBasicProject.UrunServiceReference.ProductDTO>> GetListAsync() {
            return base.Channel.GetListAsync();
        }
        
        public WcfBasicProject.UrunServiceReference.ProductDTO Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<WcfBasicProject.UrunServiceReference.ProductDTO> GetAsync() {
            return base.Channel.GetAsync();
        }
        
        public bool Add(WcfBasicProject.UrunServiceReference.ProductDTO entity) {
            return base.Channel.Add(entity);
        }
        
        public System.Threading.Tasks.Task<bool> AddAsync(WcfBasicProject.UrunServiceReference.ProductDTO entity) {
            return base.Channel.AddAsync(entity);
        }
        
        public bool Update(WcfBasicProject.UrunServiceReference.ProductDTO entity) {
            return base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(WcfBasicProject.UrunServiceReference.ProductDTO entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public bool Delete(WcfBasicProject.UrunServiceReference.ProductDTO entity) {
            return base.Channel.Delete(entity);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(WcfBasicProject.UrunServiceReference.ProductDTO entity) {
            return base.Channel.DeleteAsync(entity);
        }
    }
}
